### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by viper619**
Changed the anchor link for splunk-sdk-javascript

### CODE REVIEW

**Comment by arys-splunk** [comment]
@bparmar-splunk can you please check? Seems like a valid fix to me.

**Comment by bparmar-splunk** [comment]
Hi @arys-splunk,
Are you referring to [this](https://github.com/splunk/sdk-app-collection/pull/2/commits/293cd52a7b8f26e29561ee61b1ba3dd65102145a) fix ?
If no, please share more details.

In case of yes, it is already been completed.

**Comment by arys-splunk** [comment]
Indeed, did not spot that.
Then we can close this PR :)

**Comment by vmalaviya-splunk** [comment]
Changes have already been made. Closing the PR.

**Pull request closed without merging**
